argus:
  computer_vision:
    ros__parameters:
      cv_debug: True

      line_detection:
        color_space: 0 # 0: BGR, 1: HSV, 2: LAB
        color_min_range: [0, 0, 0]
        color_max_range: [25, 25, 25]
        max_area: 0.3  # Ratio of total area of frame
        min_area: 0.04 # Ratio of total area of frame

      line_state_classification:
        activated: True
        on_edge: True
        model_path: "~/argus_ws/models/model_grayscale.tflite"
        class_names: ['straight', 'x', 'T', 'left', 'right', 'end']
        threshold: 0.65
        queue_size: 5

      aruco_detection:
        aruco_type: 'DICT_4X4_1000'

      color_blob_detection:
        color_space: 0 # 0: BGR, 1: HSV, 2: LAB
        color_min_range: [0, 0, 0]
        color_max_range: [25, 25, 25]
        max_area: 0.1 # Ratio of total area of frame
        min_area: 0.01 # Ratio of total area of frame
