argus:
  frame_pub:
    ros__parameters:
      compressed: False
      rate: 15
      resolution: 2 # 0: 320×240, 1: 640x480, 2: 864x480, 3: 1280×720, 4: 1920×1080
      brightness: 100
      sharpness: 180
      saturation: 60
      auto_exposure: 1 # 1: disabled, 3: enabled
      exposure: 400
      gain: 35